on:
  push:
    branches:
      - chatbot_optimization
    paths:
      - 'actions/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build Action Server image and upgrade Rasa X deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_LOGIN }}/example-action-server:latest -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_LOGIN }}/example-action-server:latest

      # Add any additional steps here if you need to deploy or do anything else with the built image
